# Passing Stats and Total Points Correlation Analysis

In [1]:
import pandas as pd

Stats have been downloaded from whoscored.com

In [2]:
df = pd.read_csv('passing_stats.csv')

In [3]:
df['LB_pct'] = df.AccLB / (df.AccLB + df.InAccLB)
df['SP_pct'] = df.AccSP / (df.AccSP + df.InAccSP)

In [4]:
df[['AccLB', 'LB_pct','AccSP','SP_pct']].corrwith(df['Pts'])

AccLB     0.311360
LB_pct    0.690194
AccSP     0.731340
SP_pct    0.555249
dtype: float64

LB pct has a surprising level of correlation to points earned in the table. The amount of successful short passes has the highest correlation, which makes sense as these teams probably have the highest amount of possession.

In [5]:
df[['LB_pct']].corrwith(df['SP_pct'])

LB_pct    0.758267
dtype: float64

Long ball accuracy is very strongly correlated with short passing accuracy. Those who are accurate passers are accurate regardless of distance.

In [6]:
print 'Accurate LB Table'
df_LB = df[['Team','AccLB','LB_pct' ,'Pts']].sort_values('AccLB', ascending=False).reset_index(drop=True)
df_LB.index += 1
df_LB

Accurate LB Table

                    Team  AccLB    LB_pct  Pts
1              Tottenham   40.5  0.568022   46
2                Chelsea   36.4  0.553191   55
3          Middlesbrough   36.2  0.471969   20
4      Manchester United   35.7  0.561321   41
5                Everton   34.2  0.449409   36
6                Burnley   33.4  0.412855   26
7              Liverpool   33.2  0.495522   45
8               West Ham   33.0  0.481050   28
9         Crystal Palace   31.6  0.437068   16
10                 Stoke   31.1  0.481424   28
11               Swansea   31.0  0.483619   18
12           Southampton   30.7  0.477449   27
13                  Hull   30.2  0.425352   16
14           Bournemouth   29.9  0.473101   26
15  West Bromwich Albion   29.6  0.409405   32
16               Watford   29.2  0.410112   24
17             Leicester   27.1  0.373278   21
18       Manchester City   26.8  0.466087   43
19            Sunderland   26.7  0.395556   15
20               Arsenal   24.8  0.487230   47

In [7]:
print 'LB % Table'
df_LB_pct = df[['Team','AccLB','LB_pct' ,'Pts']].sort_values('LB_pct', ascending=False).reset_index(drop=True)
df_LB_pct.index += 1
df_LB_pct

LB % Table

                    Team  AccLB    LB_pct  Pts
1              Tottenham   40.5  0.568022   46
2      Manchester United   35.7  0.561321   41
3                Chelsea   36.4  0.553191   55
4              Liverpool   33.2  0.495522   45
5                Arsenal   24.8  0.487230   47
6                Swansea   31.0  0.483619   18
7                  Stoke   31.1  0.481424   28
8               West Ham   33.0  0.481050   28
9            Southampton   30.7  0.477449   27
10           Bournemouth   29.9  0.473101   26
11         Middlesbrough   36.2  0.471969   20
12       Manchester City   26.8  0.466087   43
13               Everton   34.2  0.449409   36
14        Crystal Palace   31.6  0.437068   16
15                  Hull   30.2  0.425352   16
16               Burnley   33.4  0.412855   26
17               Watford   29.2  0.410112   24
18  West Bromwich Albion   29.6  0.409405   32
19            Sunderland   26.7  0.395556   15
20             Leicester   27.1  0.373278   21

In [8]:
print 'Short Pass Table'
df_SP = df[['Team','AccSP', 'SP_pct','Pts']].sort_values('AccSP', ascending = False).reset_index(drop=True)
df_SP.index += 1
df_SP

Short Pass Table

                    Team  AccSP    SP_pct  Pts
1              Liverpool  472.1  0.873612   45
2        Manchester City  460.7  0.884431   43
3                Arsenal  453.3  0.869390   47
4      Manchester United  424.5  0.885482   41
5                Chelsea  407.0  0.880952   55
6              Tottenham  387.2  0.863130   46
7            Southampton  358.5  0.853368   27
8            Bournemouth  338.7  0.866019   26
9                Swansea  310.7  0.843606   18
10                  Hull  305.5  0.861048   16
11               Everton  304.9  0.842964   36
12         Middlesbrough  303.2  0.849062   20
13              West Ham  279.5  0.851096   28
14        Crystal Palace  260.6  0.820271   16
15                 Stoke  253.1  0.808626   28
16             Leicester  231.2  0.782933   21
17               Watford  224.6  0.790567   24
18            Sunderland  211.6  0.816673   15
19  West Bromwich Albion  188.8  0.789628   32
20               Burnley  187.1  0.771228   26

In [10]:
print 'SP % Table'
df_SP_pct = df[['Team','AccSP','SP_pct' ,'Pts']].sort_values('SP_pct', ascending=False).reset_index(drop=True)
df_SP_pct.index += 1
df_SP_pct

SP % Table

                    Team  AccSP    SP_pct  Pts
1      Manchester United  424.5  0.885482   41
2        Manchester City  460.7  0.884431   43
3                Chelsea  407.0  0.880952   55
4              Liverpool  472.1  0.873612   45
5                Arsenal  453.3  0.869390   47
6            Bournemouth  338.7  0.866019   26
7              Tottenham  387.2  0.863130   46
8                   Hull  305.5  0.861048   16
9            Southampton  358.5  0.853368   27
10              West Ham  279.5  0.851096   28
11         Middlesbrough  303.2  0.849062   20
12               Swansea  310.7  0.843606   18
13               Everton  304.9  0.842964   36
14        Crystal Palace  260.6  0.820271   16
15            Sunderland  211.6  0.816673   15
16                 Stoke  253.1  0.808626   28
17               Watford  224.6  0.790567   24
18  West Bromwich Albion  188.8  0.789628   32
19             Leicester  231.2  0.782933   21
20               Burnley  187.1  0.771228   26